import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import Providers from "@/lib/query-provider"

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <div className="p-4 lg:px-48">
          <Providers>
            {children}
          </Providers>
        </div>
      </body>
    </html>
  );
}
